apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pensjonskalkulator-backend
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
  ingresses:
    - https://pensjonskalkulator-backend.intern.dev.nav.no
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/health/readiness
    periodSeconds: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf" # 0000-GA-PENSJON_SAKSBEHANDLER
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: pensjonskalkulator-frontend
        - application: wonderwalled-azure
          namespace: aura
        - application: wonderwalled-idporten
          namespace: aura
    outbound:
      rules:
        - application: pdl-api
          namespace: pdl
          cluster: dev-fss
        - application: pensjon-selvbetjening-fss-gateway
          namespace: pensjonselvbetjening
          cluster: dev-fss
        - application: skjermede-personer-pip
          namespace: nom
        - application: tp-q2
          namespace: pensjonsamhandling
          cluster: dev-fss
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: pensjon-pen.dev-fss-pub.nais.io
        - host: pensjon-popp-q2.dev-fss-pub.nais.io
        - host: pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
        - host: pensjonskalkulator-unleash-api.nav.cloud.nais.io
        - host: skjermede-personer-pip.intern.dev.nav.no
        - host: test.idporten.no
        - host: tp-api-q2.dev-fss-pub.nais.io
  env:
    - name: IDPORTEN_ISSUER
      value: https://test.idporten.no
    - name: IDPORTEN_PING_URL
      value: https://test.idporten.no/.well-known/openid-configuration
    - name: FSS_GATEWAY_SERVICE_ID
      value: dev-fss:pensjonselvbetjening:pensjon-selvbetjening-fss-gateway
    - name: FSS_GATEWAY_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: NORSK_PENSJON_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: PEN_SERVICE_ID
      value: dev-fss:pensjon-q2:pensjon-pen-q2
    - name: PEN_URL
      value: https://pensjon-pen-q2.dev-fss-pub.nais.io
    - name: PENSJON_REGLER_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: PERSONDATA_SERVICE_ID
      value: dev-fss:pdl:pdl-api
    - name: PERSONDATA_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: POPP_SERVICE_ID
      value: dev-fss:pensjonopptjening:pensjon-popp-q2
    - name: POPP_URL
      value: https://pensjon-popp-q2.dev-fss-pub.nais.io
    - name: SKJERMEDE_PERSONER_SERVICE_ID
      value: dev-gcp:nom:skjermede-personer-pip
    - name: SKJERMEDE_PERSONER_URL
      value: https://skjermede-personer-pip.intern.dev.nav.no
    - name: STS_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: TJENESTEPENSJON_SERVICE_ID
      value: dev-fss:pensjonsamhandling:tp-q2
    - name: TJENESTEPENSJON_URL
      value: https://tp-api-q2.dev-fss-pub.nais.io
    - name: SERVER_ERROR_INCLUDE_STACKTRACE
      value: always
    - name: STDOUT_LOG_OUTPUT
      value: JSON
    - name: LOGGING_LEVEL
      value: DEBUG
    - name: JAVA_TOOL_OPTIONS
      value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  envFrom:
    - secret: pensjonskalkulator-backend-unleash-api-token
