apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pensjonskalkulator-backend
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - https://pensjonskalkulator-backend.intern.dev.nav.no
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/health/readiness
    periodSeconds: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
      claims: # only for testing impersonal access control
        groups:
          - id: "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf" # 0000-GA-PENSJON_SAKSBEHANDLER
          - id: "a3f91493-1ab8-4b64-a544-0a77cbba9240" # 0000-GA-Pensjon_VEILEDER
          - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
          - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
          - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
        extra:
          - NAVident
  tokenx:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "nav:pensjonssimulator:simulering" # only in dev
        - name: "nav:pensjon:mock.livsvarig.afp.offentlig"
        - name: "gabler:nav"
        - name: "spk:nav"
  accessPolicy:
    inbound:
      rules:
        - application: pensjonskalkulator-frontend
        - application: pensjonskalkulator-frontend-intern
        - application: pensjonskalkulator-frontend-ekstern
        - application: pensjonskalkulator-veiledning-frontend
        - application: pensjonskalkulator-frontend-catbox
        - application: pensjonskalkulator-veiledning-frontend-catbox
        - application: pensjonskalkulator-frontend-codebox
        - application: pensjonskalkulator-veiledning-frontend-codebox
        - application: pensjonskalkulator-frontend-coffeebox
        - application: pensjonskalkulator-veiledning-frontend-coffeebox
        - application: pensjonskalkulator-frontend-dreambox
        - application: pensjonskalkulator-veiledning-frontend-dreambox
        - application: pensjonskalkulator-frontend-magicbox
        - application: pensjonskalkulator-veiledning-frontend-magicbox
        - application: pensjonskalkulator-frontend-sandbox
        - application: pensjonskalkulator-veiledning-frontend-sandbox
        - application: pensjonskalkulator-uinnlogget-catbox
        - application: pensjonskalkulator-uinnlogget-dev
        - application: pensjonskalkulator-uinnlogget-dreambox
        - application: pensjonskalkulator-uinnlogget-magicbox
        - application: pensjonskalkulator-uinnlogget-sandbox
        - application: '*'
          namespace: pensjonskalkulator
          cluster: dev-gcp
        - application: azure-token-generator # only in dev
          namespace: nais
        - application: tokenx-token-generator # only in dev
          namespace: nais
    outbound:
      rules:
        - application: etterlatte-api
          namespace: etterlatte
        - application: pdl-api
          namespace: pdl
          cluster: dev-fss
        - application: pensjon-representasjon-q2
          namespace: pensjon-person
          cluster: dev-fss
        - application: pensjon-selvbetjening-fss-gateway
          namespace: pensjonselvbetjening
          cluster: dev-fss
        - application: pensjonssimulator
        - application: pensjon-tilgang
        - application: skjermede-personer-pip
          namespace: nom
        - application: tp-q2
          namespace: pensjonsamhandling
          cluster: dev-fss
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
        - host: pensjon-popp-q2.dev-fss-pub.nais.io
        - host: pensjon-representasjon-q2.dev-fss-pub.nais.io
        - host: pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
        - host: pensjon-testdata-facade.dev-fss-pub.nais.io # only in dev
        - host: pensjonskalkulator-unleash-api.nav.cloud.nais.io
        - host: skjermede-personer-pip.intern.dev.nav.no
        - host: tp-api-q2.dev-fss-pub.nais.io
        - host: sokos-utbetaldata.dev-fss-pub.nais.io
  env:
    - name: FSS_GATEWAY_SERVICE_ID
      value: dev-fss:pensjonselvbetjening:pensjon-selvbetjening-fss-gateway
    - name: FSS_GATEWAY_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: NORSK_PENSJON_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: NORSK_PENSJON_MOCK_URL
      value: https://pensjon-testdata-facade.dev-fss-pub.nais.io # only in dev
    - name: OMSTILLINGSSTOENAD_SERVICE_ID
      value: dev-gcp:etterlatte:etterlatte-api
    - name: OMSTILLINGSSTOENAD_URL
      value: http://etterlatte-api.etterlatte
    - name: PEN_SERVICE_ID
      value: dev-fss:pensjon-q2:pensjon-pen-q2
    - name: PEN_URL
      value: https://pensjon-pen-q2.dev-fss-pub.nais.io
    - name: PENSJON_REPRESENTASJON_SERVICE_ID
      value: dev-fss:pensjon-person:pensjon-representasjon-q2
    - name: PENSJON_REPRESENTASJON_URL
      value: https://pensjon-representasjon-q2.dev-fss-pub.nais.io
    - name: PENSJONSSIMULATOR_SERVICE_ID
      value: dev-gcp:pensjonskalkulator:pensjonssimulator
    - name: PENSJONSSIMULATOR_URL
      value: http://pensjonssimulator
    - name: PERSONDATA_SERVICE_ID
      value: dev-fss:pdl:pdl-api
    - name: PERSONDATA_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: POPP_SERVICE_ID
      value: dev-fss:pensjonopptjening:pensjon-popp-q2
    - name: POPP_URL
      value: https://pensjon-popp-q2.dev-fss-pub.nais.io
    - name: SKJERMEDE_PERSONER_SERVICE_ID
      value: dev-gcp:nom:skjermede-personer-pip
    - name: SKJERMEDE_PERSONER_URL
      value: https://skjermede-personer-pip.intern.dev.nav.no
    - name: SOKOS_UTBETALDATA_SERVICE_ID
      value: dev-fss:okonomi:sokos-utbetaldata
    - name: SOKOS_UTBETALDATA_URL
      value: https://sokos-utbetaldata.dev-fss-pub.nais.io
    - name: STS_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: TILGANGSMASKINEN_SERVICE_ID
      value: dev-gcp:tilgangsmaskin:populasjonstilgangskontroll
    - name: TILGANGSMASKINEN_TILGANG_URL
      value: http://populasjonstilgangskontroll.tilgangsmaskin
    - name: TJENESTEPENSJON_SERVICE_ID
      value: dev-fss:pensjonsamhandling:tp-q2
    - name: TJENESTEPENSJON_URL
      value: https://tp-api-q2.dev-fss-pub.nais.io
    - name: SERVER_ERROR_INCLUDE_STACKTRACE
      value: always
    - name: AUDIT_LOG_OUTPUT
      value: SYSLOG
    - name: STDOUT_LOG_OUTPUT
      value: JSON
    - name: PKB_LOGGING_LEVEL
      value: DEBUG
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_AKSIO_URL
      value: https://pensjon-afp-offentlig-mock-q2.intern.dev.nav.no/api/afp-offentlig-status/{tpnr}/hentAfpStatus/{fnr}?uttaksdato={uttaksdato}
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_AKSIO_SCOPE
      value: nav:pensjon:mock.livsvarig.afp.offentlig
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_SPK_URL
      value: https://pensjon-afp-offentlig-mock-q2.intern.dev.nav.no/api/afp-offentlig-status/{tpnr}/hentAfpStatus/{fnr}?uttaksdato={uttaksdato}
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_GABLER_URL
      value: https://pensjon-afp-offentlig-mock-q2.intern.dev.nav.no/api/afp-offentlig-status/{tpnr}/hentAfpStatus/{fnr}?uttaksdato={uttaksdato}
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_GABLER_SCOPE
      value: nav:pensjon:mock.livsvarig.afp.offentlig
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_GABLER2_URL
      value: https://pensjon-afp-offentlig-mock-q2.intern.dev.nav.no/api/afp-offentlig-status/{tpnr}/hentAfpStatus/{fnr}?uttaksdato={uttaksdato}
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_KLP_URL
      value: https://pensjon-afp-offentlig-mock-q2.intern.dev.nav.no/api/afp-offentlig-status/{tpnr}/hentAfpStatus/{fnr}?uttaksdato={uttaksdato}
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_KLP_SCOPE
      value: nav:pensjon:mock.livsvarig.afp.offentlig
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_OPF_URL
      value: https://pensjon-afp-offentlig-mock-q2.intern.dev.nav.no/api/afp-offentlig-status/{tpnr}/hentAfpStatus/{fnr}?uttaksdato={uttaksdato}
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_OPF_SCOPE
      value: nav:pensjon:mock.livsvarig.afp.offentlig
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_STOREBRAND_URL
      value: https://pensjon-afp-offentlig-mock-q2.intern.dev.nav.no/api/afp-offentlig-status/{tpnr}/hentAfpStatus/{fnr}?uttaksdato={uttaksdato}
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_STOREBRAND_SCOPE
      value: nav:pensjon:mock.livsvarig.afp.offentlig
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_STOREBRAND_PEN_URL
      value: https://pensjon-afp-offentlig-mock-q2.intern.dev.nav.no/api/afp-offentlig-status/{tpnr}/hentAfpStatus/{fnr}?uttaksdato={uttaksdato}
    - name: LIVSVARIG_AFP_OFFENTLIG_TILBYDERE_STOREBRAND_PEN_SCOPE
      value: nav:pensjon:mock.livsvarig.afp.offentlig
  envFrom:
    - secret: pensjonskalkulator-backend-unleash-api-token
    - secret: pkb-pid-encryption
