apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pensjonskalkulator-backend
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 70
  ingresses:
    - https://pensjonskalkulator-backend.intern.nav.no
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/health/readiness
    periodSeconds: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: "2"
      memory: "2048Mi"
    requests:
      cpu: "1"
      memory: "1024Mi"
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: pensjonskalkulator-frontend
    outbound:
      rules:
        - application: pdl-api
          namespace: pdl
          cluster: prod-fss
        - application: pensjon-selvbetjening-fss-gateway
          namespace: pensjonselvbetjening
          cluster: prod-fss
        - application: skjermede-personer-pip
          namespace: nom
        - application: tp
          namespace: pensjonsamhandling
          cluster: prod-fss
      external:
        - host: oidc.difi.no
        - host: pdl-api.prod-fss-pub.nais.io
        - host: pensjon-pen.prod-fss-pub.nais.io
        - host: pensjon-popp.prod-fss-pub.nais.io
        - host: pensjon-selvbetjening-fss-gateway.prod-fss-pub.nais.io
        - host: pensjonskalkulator-unleash-api.nav.cloud.nais.io
        - host: skjermede-personer-pip.intern.nav.no
        - host: tp-api.prod-fss-pub.nais.io
  env:
    - name: IDPORTEN_ISSUER
      value: https://oidc.difi.no/idporten-oidc-provider/
    - name: IDPORTEN_PING_URL
      value: https://oidc.difi.no/idporten-oidc-provider/.well-known/openid-configuration
    - name: FSS_GATEWAY_SERVICE_ID
      value: prod-fss:pensjonselvbetjening:pensjon-selvbetjening-fss-gateway
    - name: FSS_GATEWAY_URL
      value: https://pensjon-selvbetjening-fss-gateway.prod-fss-pub.nais.io
    - name: NORSK_PENSJON_URL
      value: https://pensjon-selvbetjening-fss-gateway.prod-fss-pub.nais.io
    - name: PEN_SERVICE_ID
      value: prod-fss:pensjondeployer:pensjon-pen
    - name: PEN_URL
      value: https://pensjon-pen.prod-fss-pub.nais.io
    - name: PENSJON_REGLER_URL
      value: https://pensjon-selvbetjening-fss-gateway.prod-fss-pub.nais.io
    - name: PERSONDATA_SERVICE_ID
      value: prod-fss:pdl:pdl-api
    - name: PERSONDATA_URL
      value: https://pdl-api.prod-fss-pub.nais.io
    - name: POPP_SERVICE_ID
      value: prod-fss:pensjonopptjening:pensjon-popp
    - name: POPP_URL
      value: https://pensjon-popp.prod-fss-pub.nais.io
    - name: SKJERMEDE_PERSONER_SERVICE_ID
      value: prod-gcp:nom:skjermede-personer-pip
    - name: SKJERMEDE_PERSONER_URL
      value: https://skjermede-personer-pip.intern.nav.no
    - name: STS_URL
      value: https://pensjon-selvbetjening-fss-gateway.prod-fss-pub.nais.io
    - name: TJENESTEPENSJON_SERVICE_ID
      value: prod-fss:pensjonsamhandling:tp
    - name: TJENESTEPENSJON_URL
      value: https://tp-api.prod-fss-pub.nais.io
    - name: SERVER_ERROR_INCLUDE_STACKTRACE
      value: never
    - name: AUDIT_LOG_OUTPUT
      value: SYSLOG
    - name: STDOUT_LOG_OUTPUT
      value: JSON
    - name: PKB_LOGGING_LEVEL
      value: INFO
  envFrom:
    - secret: pensjonskalkulator-backend-unleash-api-token
