apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjonskalkulator-backend
  namespace: pensjonskalkulator
  labels:
    team: pensjonskalkulator
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
  ingresses:
    - https://pensjonskalkulator-backend.intern.dev.nav.no
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    timeout: 1
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    path: /internal/health/readiness
    periodSeconds: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: pensjonskalkulator-frontend
        - application: debug-dings
          namespace: plattformsikkerhet
        - application: wonderwalled-idporten
          namespace: aura
    outbound:
      rules:
        - application: pensjon-selvbetjening-fss-gateway
          namespace: pensjonselvbetjening
          cluster: dev-fss
      external:
        - host: pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
        - host: pep-gw-q1.oera-q.local
          ports:
            - port: 9443
  env:
    - name: NORSK_PENSJON_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: PDL_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: PEN_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: PENSJON_REGLER_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: POPP_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: STS_URL
      value: https://pensjon-selvbetjening-fss-gateway.dev-fss-pub.nais.io
    - name: STDOUT_LOG_OUTPUT
      value: JSON
