package no.nav.pensjon.kalkulator.simulering

enum class SimuleringType {
    ALDERSPENSJON,
    AFP_ETTERF_ALDER,
    ALDERSPENSJON_MED_AFP_PRIVAT,
    ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG,
    ENDRING_ALDERSPENSJON,
    ENDRING_ALDERSPENSJON_MED_AFP_PRIVAT,
    ENDRING_ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG,
}
