package no.nav.pensjon.kalkulator.simulering

enum class SimuleringType {
    ALDERSPENSJON,
    PRE2025_OFFENTLIG_AFP_ETTERFULGT_AV_ALDERSPENSJON,
    ALDERSPENSJON_MED_AFP_PRIVAT,
    ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG,
    ENDRING_ALDERSPENSJON,
    ENDRING_ALDERSPENSJON_MED_AFP_PRIVAT,
    ENDRING_ALDERSPENSJON_MED_AFP_OFFENTLIG_LIVSVARIG,
}
