package no.nav.pensjon.kalkulator.avtale

enum class AvtaleUnderkategori {
    NONE,
    UNKNOWN,
    FORENINGSKOLLEKTIV,
    FORETAKSPENSJON,
    FORTSETTELSESFORSIKRING,
    FRIPOLISE,
    FRIPOLISE_MED_INVESTERINGSVALG,
    HYBRIDPENSJON_MED_GARANTERT_REGULERING,
    HYBRIDPENSJON_MED_INDIVIDUELT_INVESTERINGSVALG,
    HYBRIDPENSJON_MED_NULLGARANTI,
    INDIVIDUELL_LIVRENTE,
    INNSKUDDSPENSJON,
    IPA,
    IPS_2008,
    IPS_2017,
    KAPITALFORSIKRING,
    KOLLEKTIV_LIVRENTE,
    OPPSATT_PENSJON,
    PENSJONSBEVIS,
    PENSJONSBEVIS_MED_INDIVIDUELT_INVESTERINGSVALG,
    PENSJONSBEVIS_MED_NULLGARANTI,
    PENSJONSKAPITALBEVIS,
    PENSJONSKAPITALBEVIS_IPS_2008,
    PENSJONSKAPITALBEVIS_IPS_2017
}
