package no.nav.pensjon.kalkulator.land

/**
 * Enumerasjon av land basert på ISO 3166-1 alpha-3.
 * Kilder:
 * - pen.T_K_LAND_3_TEGN, pen.T_K_AVTALELAND
 * - https://no.wikipedia.org/wiki/ISO_3166-1
 * - https://en.wikipedia.org/wiki/ISO_3166-1
 * - https://no.wikipedia.org/wiki/De_nederlandske_Antiller
 * Sortert alfabetisk etter bokmålsnavn.
 * NB: "XUK" (ukjent/uoppgitt) er utelatt.
 */
enum class Land(val erAvtaleland: Boolean, val bokmaalNavn: String, val engelskNavn: String) {
    AFG(false, "Afghanistan", "Afghanistan"),
    ALB(false, "Albania", "Albania"),
    DZA(false, "Algerie", "Algeria"),
    ASM(false, "Amerikansk Samoa", "American Samoa"),
    AND(false, "Andorra", "Andorra"),
    AGO(false, "Angola", "Angola"),
    AIA(false, "Anguilla", "Anguilla"),
    ATA(false, "Antarktis", "Antarctica"),
    ATG(false, "Antigua og Barbuda", "Antigua and Barbuda"),
    ARG(false, "Argentina", "Argentina"),
    ARM(false, "Armenia", "Armenia"),
    ABW(false, "Aruba", "Aruba"),
    AZE(false, "Aserbajdsjan", "Azerbaijan"),
    AUS(true, "Australia", "Australia"),
    BHS(false, "Bahamas", "Bahamas"),
    BHR(false, "Bahrain", "Bahrain"),
    BGD(false, "Bangladesh", "Bangladesh"),
    BRB(false, "Barbados", "Barbados"),
    BLR(false, "Belarus", "Belarus"),
    BEL(true, "Belgia", "Belgium"),
    BLZ(false, "Belize", "Belize"),
    BEN(false, "Benin", "Benin"),
    BMU(false, "Bermuda", "Bermuda"),
    BTN(false, "Bhutan", "Bhutan"),
    BOL(false, "Bolivia", "Bolivia"),
    BES(false, "Bonaire, Sint Eustatius og Saba", "Bonaire, Sint Eustatius and Saba"),
    BIH(false, "Bosnia-Hercegovina", "Bosnia and Herzegovina"),
    BWA(false, "Botswana", "Botswana"),
    BVT(false, "Bouvetøya", "Bouvet Island"),
    BRA(false, "Brasil", "Brazil"),
    BRN(false, "Brunei", "Brunei"),
    BGR(true, "Bulgaria", "Bulgaria"),
    BFA(false, "Burkina Faso", "Burkina Faso"),
    BDI(false, "Burundi", "Burundi"),
    CAN(true, "Canada", "Canada"),
    CYM(false, "Caymanøyene", "Cayman Islands"),
    CHL(true, "Chile", "Chile"),
    CXR(false, "Christmasøya", "Christmas Island"),
    COL(false, "Colombia", "Colombia"),
    COK(false, "Cookøyene", "Cook Islands"),
    CRI(false, "Costa Rica", "Costa Rica"),
    CUB(false, "Cuba", "Cuba"),
    CUW(false, "Curaçao", "Curaçao"),
    DNK(true, "Danmark", "Denmark"),
    ARE(false, "De forente arabiske emirater", "United Arab Emirates"),
    ANT(false, "De nederlandske Antiller", "Netherlands Antilles"), // oppløst 10. oktober 2010
    ATF(false, "De franske sørterritorier", "French Southern Territories"),
    DOM(false, "Den dominikanske republikk", "Dominican Republic"),
    CAF(false, "Den sentralafrikanske republikk", "Central African Republic"),
    IOT(false, "Det britiske territoriet i Indiahavet", "British Indian Ocean Territory"),
    DJI(false, "Djibouti", "Djibouti"),
    DMA(false, "Dominica", "Dominica"),
    ECU(false, "Ecuador", "Ecuador"),
    EGY(false, "Egypt", "Egypt"),
    GNQ(false, "Ekvatorial-Guinea", "Equatorial Guinea"),
    SLV(false, "El Salvador", "El Salvador"),
    CIV(false, "Elfenbenskysten", "Ivory Coast"),
    ERI(false, "Eritrea", "Eritrea"),
    EST(true, "Estland", "Estonia"),
    SWZ(false, "Eswatini", "Eswatini"),
    ETH(false, "Etiopia", "Ethiopia"),
    FLK(false, "Falklandsøyene", "Falkland Islands (Malvinas)"),
    FJI(false, "Fiji", "Fiji"),
    PHL(false, "Filippinene", "Philippines"),
    FIN(true, "Finland", "Finland"),
    FRA(true, "Frankrike", "France"),
    GUF(true, "Fransk Guyana", "French Guiana"),
    PYF(false, "Fransk Polynesia", "French Polynesia"),
    FRO(true, "Færøyene", "Faroe Islands"),
    GAB(false, "Gabon", "Gabon"),
    GMB(false, "Gambia", "Gambia"),
    GEO(false, "Georgia", "Georgia"),
    GHA(false, "Ghana", "Ghana"),
    GIB(false, "Gibraltar", "Gibraltar"),
    GRD(false, "Grenada", "Grenada"),
    GRL(true, "Grønland", "Greenland"),
    GLP(true, "Guadeloupe", "Guadeloupe"),
    GUM(false, "Guam", "Guam"),
    GTM(false, "Guatemala", "Guatemala"),
    GGY(false, "Guernsey", "Guernsey"),
    GIN(false, "Guinea", "Guinea"),
    GNB(false, "Guinea-Bissau", "Guinea-Bissau"),
    GUY(false, "Guyana", "Guyana"),
    HTI(false, "Haiti", "Haiti"),
    HMD(false, "Heard- og McDonaldøyene", "Heard Island and McDonald Islands"),
    GRC(true, "Hellas", "Greece"),
    HND(false, "Honduras", "Honduras"),
    HKG(false, "Hongkong", "Hong Kong"),
    IND(true, "India", "India"),
    IDN(false, "Indonesia", "Indonesia"),
    IRQ(false, "Irak", "Iraq"),
    IRN(false, "Iran", "Iran"),
    IRL(true, "Irland", "Ireland"),
    ISL(true, "Island", "Iceland"),
    IMN(true, "Isle of Man", "Isle of Man"),
    ISR(true, "Israel", "Israel"),
    ITA(true, "Italia", "Italy"),
    JAM(false, "Jamaica", "Jamaica"),
    JPN(false, "Japan", "Japan"),
    YEM(false, "Jemen", "Yemen"),
    JEY(true, "Jersey", "Jersey"),
    VIR(false, "Jomfruøyene (De amerikanske)", "Virgin Islands (U.S.)"),
    VGB(false, "Jomfruøyene (De britiske)", "Virgin Islands (British)"),
    JOR(false, "Jordan", "Jordan"),
    KHM(false, "Kambodsja", "Cambodia"),
    CMR(false, "Kamerun", "Cameroon"),
    CPV(false, "Kapp Verde", "Cabo Verde"),
    KAZ(false, "Kasakhstan", "Kazakhstan"),
    KEN(false, "Kenya", "Kenya"),
    CHN(false, "Kina", "China"),
    KGZ(false, "Kirgisistan", "Kyrgyzstan"),
    KIR(false, "Kiribati", "Kiribati"),
    CCK(false, "Kokosøyene (Keelingøyene)", " Cocos (Keeling) Islands"),
    COM(false, "Komorene", "Comoros"),
    COD(false, "Kongo-Kinshasa", "Congo-Kinshasa"),
    COG(false, "Kongo-Brazzaville", "Congo-Brazzaville"),
    XXK(false, "Kosovo", "Kosovo"),
    HRV(true, "Kroatia", "Croatia"),
    KWT(false, "Kuwait", "Kuwait"),
    CYP(true, "Kypros", "Cyprus"),
    LAO(false, "Laos", "Laos"),
    LVA(true, "Latvia", "Latvia"),
    LSO(false, "Lesotho", "Lesotho"),
    LBN(false, "Libanon", "Lebanon"),
    LBR(false, "Liberia", "Liberia"),
    LBY(false, "Libya", "Libya"),
    LIE(true, "Liechtenstein", "Liechtenstein"),
    LTU(true, "Litauen", "Lithuania"),
    LUX(true, "Luxembourg", "Luxembourg"),
    MAC(false, "Macao", "Macao"),
    MDG(false, "Madagaskar", "Madagascar"),
    MWI(false, "Malawi", "Malawi"),
    MYS(false, "Malaysia", "Malaysia"),
    MDV(false, "Maldivene", "Maldives"),
    MLI(false, "Mali", "Mali"),
    MLT(true, "Malta", "Malta"),
    MAR(false, "Marokko", "Morocco"),
    MHL(false, "Marshalløyene", "Marshall Islands"),
    MTQ(true, "Martinique", "Martinique"),
    MRT(false, "Mauritania", "Mauritania"),
    MUS(false, "Mauritius", "Mauritius"),
    MYT(false, "Mayotte", "Mayotte"),
    MEX(false, "Mexico", "Mexico"),
    FSM(false, "Mikronesiaføderasjonen", "Micronesia"),
    MDA(false, "Moldova", "Moldova"),
    MCO(false, "Monaco", "Monaco"),
    MNG(false, "Mongolia", "Mongolia"),
    MNE(false, "Montenegro", "Montenegro"),
    MSR(false, "Montserrat", "Montserrat"),
    MOZ(false, "Mosambik", "Mozambique"),
    MMR(false, "Myanmar (Burma)", "Myanmar (Burma)"),
    NAM(false, "Namibia", "Namibia"),
    NRU(false, "Nauru", "Nauru"),
    NLD(true, "Nederland", "Netherlands"),
    NPL(false, "Nepal", "Nepal"),
    NZL(false, "New Zealand", "New Zealand"),
    NIC(false, "Nicaragua", "Nicaragua"),
    NER(false, "Niger", "Niger"),
    NGA(false, "Nigeria", "Nigeria"),
    NIU(false, "Niue", "Niue"),
    PRK(false, "Nord-Korea", "North Korea"),
    MKD(false, "Nord-Makedonia", "North Macedonia"),
    MNP(false, "Nord-Marianene", "Northern Mariana Islands"),
    NFK(false, "Norfolkøya", "Norfolk Island"),
    NOR(true, "Norge", "Norway"),
    NCL(false, "Ny-Caledonia", "New Caledonia"),
    OMN(false, "Oman", "Oman"),
    PAK(false, "Pakistan", "Pakistan"),
    PLW(false, "Palau", "Palau"),
    PSE(false, "Palestina", "Palestina"),
    PAN(false, "Panama", "Panama"),
    PNG(false, "Papua Ny-Guinea", "Papua New Guinea"),
    PRY(false, "Paraguay", "Paraguay"),
    PER(false, "Peru", "Peru"),
    PCN(false, "Pitcairn", "Pitcairn"),
    POL(true, "Polen", "Poland"),
    PRT(true, "Portugal", "Portugal"),
    PRI(false, "Puerto Rico", "Puerto Rico"),
    QAT(false, "Qatar", "Qatar"),
    QEB(true, "Quebec", "Quebec"), // NB: Ikke et land, men provins i Canada; Quebec har trygdeavtale med Norge
    REU(true, "Réunion", "Réunion"),
    ROU(true, "Romania", "Romania"),
    RUS(false, "Russland", "Russia"),
    RWA(false, "Rwanda", "Rwanda"),
    BLM(false, "Saint Barthélemy", "Saint Barthélemy"),
    SHN(false, "St. Helena, Ascension og Tristan da Cunha", "Saint Helena, Ascension and Tristan da Cunha"),
    KNA(false, "Saint Kitts og Nevis", "Saint Kitts and Nevis"),
    LCA(false, "Saint Lucia", "Saint Lucia"),
    MAF(false, "Saint-Martin", "Saint Martin"),
    SPM(false, "Saint-Pierre og Miquelon", "Saint Pierre and Miquelon"),
    VCT(false, "Saint Vincent og Grenadinene", "Saint Vincent and the Grenadines"),
    SLB(false, "Salomonøyene", "Solomon Islands"),
    WSM(false, "Samoa", "Samoa"),
    SMR(false, "San Marino", "San Marino"),
    STP(false, "São Tomé og Príncipe", "Sao Tome and Principe"),
    SAU(false, "Saudi-Arabia", "Saudi Arabia"),
    SEN(false, "Senegal", "Senegal"),
    SRB(false, "Serbia", "Serbia"),
    SYC(false, "Seychellene", "Seychelles"),
    SLE(false, "Sierra Leone", "Sierra Leone"),
    SGP(false, "Singapore", "Singapore"),
    SXM(false, "Sint Maarten", "Sint Maarten"),
    SVK(true, "Slovakia", "Slovakia"),
    SVN(true, "Slovenia", "Slovenia"),
    SOM(false, "Somalia", "Somalia"),
    ESP(true, "Spania", "Spain"),
    LKA(false, "Sri Lanka", "Sri Lanka"),
    XXX(false, "statsløs", "stateless"),
    GBR(true, "Storbritannia", "Britain (United Kingdom)"),
    SDN(false, "Sudan", "Sudan"),
    SUR(false, "Surinam", "Suriname"),
    SJM(false, "Svalbard og Jan Mayen", "Svalbard and Jan Mayen"),
    CHE(true, "Sveits", "Switzerland"),
    SWE(true, "Sverige", "Sweden"),
    SYR(false, "Syria", "Syria"),
    ZAF(false, "Sør-Afrika", "South Africa"),
    SGS(false, "Sør-Georgia og Sør-Sandwichøyene", "South Georgia and the South Sandwich Islands"),
    KOR(true, "Sør-Korea", "South Korea"),
    SSD(false, "Sør-Sudan", "South Sudan"),
    TJK(false, "Tadsjikistan", "Tajikistan"),
    TWN(false, "Taiwan", "Taiwan"),
    TZA(false, "Tanzania", "Tanzania"),
    TCD(false, "Tchad", "Chad"),
    THA(false, "Thailand", "Thailand"),
    TGO(false, "Togo", "Togo"),
    TKL(false, "Tokelau", "Tokelau"),
    TON(false, "Tonga", "Tonga"),
    TTO(false, "Trinidad og Tobago", "Trinidad and Tobago"),
    CZE(true, "Tsjekkia", "Czechia"),
    TUN(false, "Tunisia", "Tunisia"),
    TKM(false, "Turkmenistan", "Turkmenistan"),
    TCA(false, "Turks- og Caicosøyene", "Turks and Caicos Islands"),
    TUV(false, "Tuvalu", "Tuvalu"),
    TUR(false, "Tyrkia", "Turkey"),
    DEU(true, "Tyskland", "Germany"),
    USA(true, "USA", "USA"),
    UGA(false, "Uganda", "Uganda"),
    UKR(false, "Ukraina", "Ukraine"),
    HUN(true, "Ungarn", "Hungary"),
    URY(false, "Uruguay", "Uruguay"),
    UMI(false, "USAs ytre småøyer", "United States Minor Outlying Islands"),
    UZB(false, "Usbekistan", "Uzbekistan"),
    VUT(false, "Vanuatu", "Vanuatu"),
    VAT(false, "Vatikanstaten", "Vatican City"),
    VEN(false, "Venezuela", "Venezuela"),
    ESH(false, "Vest-Sahara", "Western Sahara"),
    VNM(false, "Vietnam", "Vietnam"),
    WLF(false, "Wallis og Futuna", "Wallis and Futuna"),
    ZMB(false, "Zambia", "Zambia"),
    ZWE(false, "Zimbabwe", "Zimbabwe"),
    TLS(false, "Øst-Timor", "East Timor"),
    AUT(true, "Østerrike", "Austria"),
    ALA(false, "Åland", "Åland")
}
