package no.nav.pensjon.kalkulator.land

/**
 * Enumerasjon av land basert på ISO 3166-1 alpha-3.
 * Kilder:
 * - pen.T_K_LAND_3_TEGN, pen.T_K_AVTALELAND
 * - pensjon-pen: LandMedRettTilOpptjeningAvTrygdetidCode (kravOmArbeid)
 * - https://navno.sharepoint.com/sites/fag-og-ytelser-eos-lovvalg-medlemskap/SitePages/Oversikt-over-land-og-omr%C3%A5der-som-er-omfattet-av-E%C3%98S-reglene-om-trygdekoordinering.aspx
 * - https://no.wikipedia.org/wiki/ISO_3166-1
 * - https://en.wikipedia.org/wiki/ISO_3166-1
 * - https://no.wikipedia.org/wiki/De_nederlandske_Antiller
 * Sortert alfabetisk etter bokmålsnavn.
 * NB: "XUK" (ukjent/uoppgitt) er utelatt.
 */
enum class Land(
    val erAvtaleland: Boolean,
    val kravOmArbeid: Boolean?, // only relevant if erAvtaleland = true
    val bokmaalNavn: String,
    val engelskNavn: String
) {
    AFG(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Afghanistan", engelskNavn = "Afghanistan"),
    ALB(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Albania", engelskNavn = "Albania"),
    DZA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Algerie", engelskNavn = "Algeria"),
    ASM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Amerikansk Samoa", engelskNavn = "American Samoa"),
    AND(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Andorra", engelskNavn = "Andorra"),
    AGO(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Angola", engelskNavn = "Angola"),
    AIA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Anguilla", engelskNavn = "Anguilla"),
    ATA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Antarktis", engelskNavn = "Antarctica"),
    ATG(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Antigua og Barbuda", engelskNavn = "Antigua and Barbuda"),
    ARG(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Argentina", engelskNavn = "Argentina"),
    ARM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Armenia", engelskNavn = "Armenia"),
    ABW(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Aruba", engelskNavn = "Aruba"),
    AZE(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Aserbajdsjan", engelskNavn = "Azerbaijan"),
    AUS(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Australia", engelskNavn = "Australia"),
    BHS(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Bahamas", engelskNavn = "Bahamas"),
    BHR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Bahrain", engelskNavn = "Bahrain"),
    BGD(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Bangladesh", engelskNavn = "Bangladesh"),
    BRB(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Barbados", engelskNavn = "Barbados"),
    BLR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Belarus", engelskNavn = "Belarus"),
    BEL(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Belgia", engelskNavn = "Belgium"),
    BLZ(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Belize", engelskNavn = "Belize"),
    BEN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Benin", engelskNavn = "Benin"),
    BMU(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Bermuda", engelskNavn = "Bermuda"),
    BTN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Bhutan", engelskNavn = "Bhutan"),
    BOL(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Bolivia", engelskNavn = "Bolivia"),
    BES(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Bonaire, Sint Eustatius og Saba", engelskNavn = "Bonaire, Sint Eustatius and Saba"),
    BIH(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Bosnia-Hercegovina", engelskNavn = "Bosnia and Herzegovina"),
    BWA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Botswana", engelskNavn = "Botswana"),
    BVT(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Bouvetøya", engelskNavn = "Bouvet Island"),
    BRA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Brasil", engelskNavn = "Brazil"),
    BRN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Brunei", engelskNavn = "Brunei"),
    BGR(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Bulgaria", engelskNavn = "Bulgaria"),
    BFA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Burkina Faso", engelskNavn = "Burkina Faso"),
    BDI(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Burundi", engelskNavn = "Burundi"),
    CAN(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Canada (utenom Quebec)", engelskNavn = "Canada (except Quebec)"),
    QEB(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Canada (Quebec)", engelskNavn = "Canada (Quebec)"), // provinsen Quebec har egen trygdeavtale med Norge
    CYM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Caymanøyene", engelskNavn = "Cayman Islands"),
    CHL(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Chile", engelskNavn = "Chile"),
    CXR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Christmasøya", engelskNavn = "Christmas Island"),
    COL(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Colombia", engelskNavn = "Colombia"),
    COK(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Cookøyene", engelskNavn = "Cook Islands"),
    CRI(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Costa Rica", engelskNavn = "Costa Rica"),
    CUB(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Cuba", engelskNavn = "Cuba"),
    CUW(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Curaçao", engelskNavn = "Curaçao"),
    DNK(erAvtaleland = true, kravOmArbeid = false, bokmaalNavn = "Danmark", engelskNavn = "Denmark"),
    ARE(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "De forente arabiske emirater", engelskNavn = "United Arab Emirates"),
    ANT(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "De nederlandske Antiller", engelskNavn = "Netherlands Antilles"), // oppløst 10. oktober 2010
    ATF(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "De franske sørterritorier", engelskNavn = "French Southern Territories"),
    DOM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Den dominikanske republikk", engelskNavn = "Dominican Republic"),
    CAF(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Den sentralafrikanske republikk", engelskNavn = "Central African Republic"),
    IOT(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Det britiske territoriet i Indiahavet", engelskNavn = "British Indian Ocean Territory"),
    DJI(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Djibouti", engelskNavn = "Djibouti"),
    DMA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Dominica", engelskNavn = "Dominica"),
    ECU(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Ecuador", engelskNavn = "Ecuador"),
    EGY(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Egypt", engelskNavn = "Egypt"),
    GNQ(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Ekvatorial-Guinea", engelskNavn = "Equatorial Guinea"),
    SLV(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "El Salvador", engelskNavn = "El Salvador"),
    CIV(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Elfenbenskysten", engelskNavn = "Ivory Coast"),
    ERI(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Eritrea", engelskNavn = "Eritrea"),
    EST(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Estland", engelskNavn = "Estonia"),
    SWZ(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Eswatini", engelskNavn = "Eswatini"),
    ETH(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Etiopia", engelskNavn = "Ethiopia"),
    FLK(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Falklandsøyene", engelskNavn = "Falkland Islands (Malvinas)"),
    FJI(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Fiji", engelskNavn = "Fiji"),
    PHL(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Filippinene", engelskNavn = "Philippines"),
    FIN(erAvtaleland = true, kravOmArbeid = false, bokmaalNavn = "Finland", engelskNavn = "Finland"),
    FRA(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Frankrike", engelskNavn = "France"),
    GUF(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Fransk Guyana", engelskNavn = "French Guiana"),
    PYF(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Fransk Polynesia", engelskNavn = "French Polynesia"),
    FRO(erAvtaleland = true, kravOmArbeid = false, bokmaalNavn = "Færøyene", engelskNavn = "Faroe Islands"),
    GAB(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Gabon", engelskNavn = "Gabon"),
    GMB(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Gambia", engelskNavn = "Gambia"),
    GEO(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Georgia", engelskNavn = "Georgia"),
    GHA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Ghana", engelskNavn = "Ghana"),
    GIB(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Gibraltar", engelskNavn = "Gibraltar"),
    GRD(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Grenada", engelskNavn = "Grenada"),
    GRL(erAvtaleland = true, kravOmArbeid = false, bokmaalNavn = "Grønland", engelskNavn = "Greenland"),
    GLP(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Guadeloupe", engelskNavn = "Guadeloupe"),
    GUM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Guam", engelskNavn = "Guam"),
    GTM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Guatemala", engelskNavn = "Guatemala"),
    GGY(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Guernsey", engelskNavn = "Guernsey"),
    GIN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Guinea", engelskNavn = "Guinea"),
    GNB(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Guinea-Bissau", engelskNavn = "Guinea-Bissau"),
    GUY(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Guyana", engelskNavn = "Guyana"),
    HTI(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Haiti", engelskNavn = "Haiti"),
    HMD(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Heard- og McDonaldøyene", engelskNavn = "Heard Island and McDonald Islands"),
    GRC(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Hellas", engelskNavn = "Greece"),
    HND(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Honduras", engelskNavn = "Honduras"),
    HKG(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Hongkong", engelskNavn = "Hong Kong"),
    IND(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "India", engelskNavn = "India"),
    IDN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Indonesia", engelskNavn = "Indonesia"),
    IRQ(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Irak", engelskNavn = "Iraq"),
    IRN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Iran", engelskNavn = "Iran"),
    IRL(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Irland", engelskNavn = "Ireland"),
    ISL(erAvtaleland = true, kravOmArbeid = false, bokmaalNavn = "Island", engelskNavn = "Iceland"),
    ISR(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Israel", engelskNavn = "Israel"),
    ITA(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Italia", engelskNavn = "Italy"),
    JAM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Jamaica", engelskNavn = "Jamaica"),
    JPN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Japan", engelskNavn = "Japan"),
    YEM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Jemen", engelskNavn = "Yemen"),
    JEY(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Jersey", engelskNavn = "Jersey"),
    VIR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Jomfruøyene (De amerikanske)", engelskNavn = "Virgin Islands (U.S.)"),
    VGB(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Jomfruøyene (De britiske)", engelskNavn = "Virgin Islands (British)"),
    JOR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Jordan", engelskNavn = "Jordan"),
    KHM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kambodsja", engelskNavn = "Cambodia"),
    CMR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kamerun", engelskNavn = "Cameroon"),
    CPV(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kapp Verde", engelskNavn = "Cabo Verde"),
    KAZ(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kasakhstan", engelskNavn = "Kazakhstan"),
    KEN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kenya", engelskNavn = "Kenya"),
    CHN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kina", engelskNavn = "China"),
    KGZ(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kirgisistan", engelskNavn = "Kyrgyzstan"),
    KIR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kiribati", engelskNavn = "Kiribati"),
    CCK(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kokosøyene (Keelingøyene)", engelskNavn = " Cocos (Keeling) Islands"),
    COM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Komorene", engelskNavn = "Comoros"),
    COD(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kongo-Kinshasa", engelskNavn = "Congo-Kinshasa"),
    COG(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kongo-Brazzaville", engelskNavn = "Congo-Brazzaville"),
    XXK(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kosovo", engelskNavn = "Kosovo"),
    HRV(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Kroatia", engelskNavn = "Croatia"),
    KWT(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Kuwait", engelskNavn = "Kuwait"),
    CYP(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Kypros", engelskNavn = "Cyprus"),
    LAO(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Laos", engelskNavn = "Laos"),
    LVA(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Latvia", engelskNavn = "Latvia"),
    LSO(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Lesotho", engelskNavn = "Lesotho"),
    LBN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Libanon", engelskNavn = "Lebanon"),
    LBR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Liberia", engelskNavn = "Liberia"),
    LBY(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Libya", engelskNavn = "Libya"),
    LIE(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Liechtenstein", engelskNavn = "Liechtenstein"),
    LTU(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Litauen", engelskNavn = "Lithuania"),
    LUX(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Luxembourg", engelskNavn = "Luxembourg"),
    MAC(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Macao", engelskNavn = "Macao"),
    MDG(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Madagaskar", engelskNavn = "Madagascar"),
    MWI(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Malawi", engelskNavn = "Malawi"),
    MYS(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Malaysia", engelskNavn = "Malaysia"),
    MDV(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Maldivene", engelskNavn = "Maldives"),
    MLI(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Mali", engelskNavn = "Mali"),
    MLT(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Malta", engelskNavn = "Malta"),
    IMN(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Man", engelskNavn = "Isle of Man"),
    MAR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Marokko", engelskNavn = "Morocco"),
    MHL(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Marshalløyene", engelskNavn = "Marshall Islands"),
    MTQ(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Martinique", engelskNavn = "Martinique"),
    MRT(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Mauritania", engelskNavn = "Mauritania"),
    MUS(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Mauritius", engelskNavn = "Mauritius"),
    MYT(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Mayotte", engelskNavn = "Mayotte"),
    MEX(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Mexico", engelskNavn = "Mexico"),
    FSM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Mikronesiaføderasjonen", engelskNavn = "Micronesia"),
    MDA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Moldova", engelskNavn = "Moldova"),
    MCO(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Monaco", engelskNavn = "Monaco"),
    MNG(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Mongolia", engelskNavn = "Mongolia"),
    MNE(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Montenegro", engelskNavn = "Montenegro"),
    MSR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Montserrat", engelskNavn = "Montserrat"),
    MOZ(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Mosambik", engelskNavn = "Mozambique"),
    MMR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Myanmar (Burma)", engelskNavn = "Myanmar (Burma)"),
    NAM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Namibia", engelskNavn = "Namibia"),
    NRU(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Nauru", engelskNavn = "Nauru"),
    NLD(erAvtaleland = true, kravOmArbeid = false, bokmaalNavn = "Nederland", engelskNavn = "Netherlands"),
    NPL(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Nepal", engelskNavn = "Nepal"),
    NZL(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "New Zealand", engelskNavn = "New Zealand"),
    NIC(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Nicaragua", engelskNavn = "Nicaragua"),
    NER(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Niger", engelskNavn = "Niger"),
    NGA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Nigeria", engelskNavn = "Nigeria"),
    NIU(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Niue", engelskNavn = "Niue"),
    PRK(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Nord-Korea", engelskNavn = "North Korea"),
    MKD(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Nord-Makedonia", engelskNavn = "North Macedonia"),
    MNP(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Nord-Marianene", engelskNavn = "Northern Mariana Islands"),
    NFK(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Norfolkøya", engelskNavn = "Norfolk Island"),
    NOR(erAvtaleland = true, kravOmArbeid = false, bokmaalNavn = "Norge", engelskNavn = "Norway"),
    NCL(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Ny-Caledonia", engelskNavn = "New Caledonia"),
    OMN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Oman", engelskNavn = "Oman"),
    PAK(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Pakistan", engelskNavn = "Pakistan"),
    PLW(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Palau", engelskNavn = "Palau"),
    PSE(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Palestina", engelskNavn = "Palestina"),
    PAN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Panama", engelskNavn = "Panama"),
    PNG(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Papua Ny-Guinea", engelskNavn = "Papua New Guinea"),
    PRY(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Paraguay", engelskNavn = "Paraguay"),
    PER(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Peru", engelskNavn = "Peru"),
    PCN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Pitcairn", engelskNavn = "Pitcairn"),
    POL(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Polen", engelskNavn = "Poland"),
    PRT(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Portugal", engelskNavn = "Portugal"),
    PRI(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Puerto Rico", engelskNavn = "Puerto Rico"),
    QAT(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Qatar", engelskNavn = "Qatar"),
    REU(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Réunion", engelskNavn = "Réunion"),
    ROU(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Romania", engelskNavn = "Romania"),
    RUS(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Russland", engelskNavn = "Russia"),
    RWA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Rwanda", engelskNavn = "Rwanda"),
    BLM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Saint Barthélemy", engelskNavn = "Saint Barthélemy"),
    SHN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "St. Helena, Ascension og Tristan da Cunha", engelskNavn = "Saint Helena, Ascension and Tristan da Cunha"),
    KNA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Saint Kitts og Nevis", engelskNavn = "Saint Kitts and Nevis"),
    LCA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Saint Lucia", engelskNavn = "Saint Lucia"),
    MAF(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Saint-Martin", engelskNavn = "Saint Martin"),
    SPM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Saint-Pierre og Miquelon", engelskNavn = "Saint Pierre and Miquelon"),
    VCT(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Saint Vincent og Grenadinene", engelskNavn = "Saint Vincent and the Grenadines"),
    SLB(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Salomonøyene", engelskNavn = "Solomon Islands"),
    WSM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Samoa", engelskNavn = "Samoa"),
    SMR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "San Marino", engelskNavn = "San Marino"),
    STP(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "São Tomé og Príncipe", engelskNavn = "Sao Tome and Principe"),
    SAU(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Saudi-Arabia", engelskNavn = "Saudi Arabia"),
    SEN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Senegal", engelskNavn = "Senegal"),
    SRB(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Serbia", engelskNavn = "Serbia"),
    SYC(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Seychellene", engelskNavn = "Seychelles"),
    SLE(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Sierra Leone", engelskNavn = "Sierra Leone"),
    SGP(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Singapore", engelskNavn = "Singapore"),
    SXM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Sint Maarten", engelskNavn = "Sint Maarten"),
    SVK(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Slovakia", engelskNavn = "Slovakia"),
    SVN(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Slovenia", engelskNavn = "Slovenia"),
    SOM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Somalia", engelskNavn = "Somalia"),
    ESP(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Spania", engelskNavn = "Spain"),
    LKA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Sri Lanka", engelskNavn = "Sri Lanka"),
    XXX(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "statsløs", engelskNavn = "stateless"),
    GBR(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Storbritannia", engelskNavn = "Britain (United Kingdom)"),
    SDN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Sudan", engelskNavn = "Sudan"),
    SUR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Surinam", engelskNavn = "Suriname"),
    SJM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Svalbard og Jan Mayen", engelskNavn = "Svalbard and Jan Mayen"),
    CHE(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Sveits", engelskNavn = "Switzerland"),
    SWE(erAvtaleland = true, kravOmArbeid = false, bokmaalNavn = "Sverige", engelskNavn = "Sweden"),
    SYR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Syria", engelskNavn = "Syria"),
    ZAF(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Sør-Afrika", engelskNavn = "South Africa"),
    SGS(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Sør-Georgia og Sør-Sandwichøyene", engelskNavn = "South Georgia and the South Sandwich Islands"),
    KOR(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Sør-Korea", engelskNavn = "South Korea"),
    SSD(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Sør-Sudan", engelskNavn = "South Sudan"),
    TJK(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Tadsjikistan", engelskNavn = "Tajikistan"),
    TWN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Taiwan", engelskNavn = "Taiwan"),
    TZA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Tanzania", engelskNavn = "Tanzania"),
    TCD(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Tchad", engelskNavn = "Chad"),
    THA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Thailand", engelskNavn = "Thailand"),
    TGO(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Togo", engelskNavn = "Togo"),
    TKL(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Tokelau", engelskNavn = "Tokelau"),
    TON(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Tonga", engelskNavn = "Tonga"),
    TTO(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Trinidad og Tobago", engelskNavn = "Trinidad and Tobago"),
    CZE(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Tsjekkia", engelskNavn = "Czechia"),
    TUN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Tunisia", engelskNavn = "Tunisia"),
    TKM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Turkmenistan", engelskNavn = "Turkmenistan"),
    TCA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Turks- og Caicosøyene", engelskNavn = "Turks and Caicos Islands"),
    TUV(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Tuvalu", engelskNavn = "Tuvalu"),
    TUR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Tyrkia", engelskNavn = "Turkey"),
    DEU(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Tyskland", engelskNavn = "Germany"),
    USA(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "USA", engelskNavn = "USA"),
    UGA(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Uganda", engelskNavn = "Uganda"),
    UKR(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Ukraina", engelskNavn = "Ukraine"),
    HUN(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Ungarn", engelskNavn = "Hungary"),
    URY(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Uruguay", engelskNavn = "Uruguay"),
    UMI(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "USAs ytre småøyer", engelskNavn = "United States Minor Outlying Islands"),
    UZB(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Usbekistan", engelskNavn = "Uzbekistan"),
    VUT(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Vanuatu", engelskNavn = "Vanuatu"),
    VAT(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Vatikanstaten", engelskNavn = "Vatican City"),
    VEN(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Venezuela", engelskNavn = "Venezuela"),
    ESH(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Vest-Sahara", engelskNavn = "Western Sahara"),
    VNM(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Vietnam", engelskNavn = "Vietnam"),
    WLF(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Wallis og Futuna", engelskNavn = "Wallis and Futuna"),
    ZMB(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Zambia", engelskNavn = "Zambia"),
    ZWE(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Zimbabwe", engelskNavn = "Zimbabwe"),
    TLS(erAvtaleland = false, kravOmArbeid = null, bokmaalNavn = "Øst-Timor", engelskNavn = "East Timor"),
    AUT(erAvtaleland = true, kravOmArbeid = true, bokmaalNavn = "Østerrike", engelskNavn = "Austria"),
    ALA(erAvtaleland = true, kravOmArbeid = false, bokmaalNavn = "Åland", engelskNavn = "Åland") // NB: Not avtaleland in PEN (Aug 2024)
}
