package no.nav.pensjon.kalkulator.land

enum class Land(val erAvtaleland: Boolean, val bokmaalNavn: String) {
    AFG(false, "Afghanistan"),
    ALB(false, "Albania"),
    DZA(false, "Algerie"),
    ASM(false, "Am. Samoa"),
    AND(false, "Andorra"),
    AGO(false, "Angola"),
    AIA(false, "Anguilla"),
    ATA(false, "Antarktis"),
    ATG(false, "Antigua Og Barbuda"),
    ARG(false, "Argentina"),
    ARM(false, "Armenia"),
    ABW(false, "Aruba"),
    AZE(false, "Aserbajdsjan"),
    AUS(true, "Australia"),
    BHS(false, "Bahamas"),
    BHR(false, "Bahrain"),
    BGD(false, "Bangladesh"),
    BRB(false, "Barbados"),
    BLR(false, "Belarus"),
    BEL(true, "Belgia"),
    BLZ(false, "Belize"),
    BEN(false, "Benin"),
    BMU(false, "Bermuda"),
    BTN(false, "Bhutan"),
    BOL(false, "Bolivia"),
    BES(false, "Bonaire, Sint Eustatius og Saba"),
    BIH(false, "Bosnia-Hercegovina"),
    BWA(false, "Botswana"),
    BVT(false, "Bouvetøya"),
    BRA(false, "Brasil"),
    BRN(false, "Brunei"),
    BGR(true, "Bulgaria"),
    BFA(false, "Burkina Faso"),
    BDI(false, "Burundi"),
    CAN(true, "Canada"),
    CYM(false, "Caymanøyene"),
    CHL(true, "Chile"),
    CXR(false, "Christmasøya"),
    COL(false, "Colombia"),
    COK(false, "Cookøyene"),
    CRI(false, "Costa Rica"),
    CUB(false, "Cuba"),
    CUW(false, "Curacao"),
    DNK(true, "Danmark"),
    ARE(false, "De Forente Arabiske Emirater"),
    ANT(false, "De Nederlandske Antillene"),
    VIR(false, "De amerikanske Jomfruøyer"),
    VGB(false, "De britiske Jomfruøyer"),
    ATF(false, "De franske territoriene i sør"),
    DOM(false, "Den Dominikanske Republikk"),
    CAF(false, "Den Sentralafrikanske Republikk"),
    IOT(false, "Det britiske territoriet i Indiahavet"),
    DJI(false, "Djibouti"),
    DMA(false, "Dominica"),
    ECU(false, "Ecuador"),
    EGY(false, "Egypt"),
    GNQ(false, "Ekvatorial-Guinea"),
    SLV(false, "El Salvador"),
    CIV(false, "Elfenbenskysten"),
    ERI(false, "Eritrea"),
    EST(true, "Estland"),
    SWZ(false, "Eswatini"),
    ETH(false, "Etiopia"),
    FLK(false, "Falklandsøyene"),
    FJI(false, "Fiji"),
    PHL(false, "Filippinene"),
    FIN(true, "Finland"),
    FRA(true, "Frankrike"),
    GUF(true, "Fransk Guyana"),
    PYF(false, "Fransk Polynesia"),
    FRO(true, "Færøyene"),
    GAB(false, "Gabon"),
    GMB(false, "Gambia"),
    GEO(false, "Georgia"),
    GHA(false, "Ghana"),
    GIB(false, "Gibraltar"),
    GRD(false, "Grenada"),
    GRL(true, "Grønland"),
    GLP(true, "Guadeloupe"),
    GUM(false, "Guam"),
    GTM(false, "Guatemala"),
    GGY(false, "Guernsey"),
    GIN(false, "Guinea"),
    GNB(false, "Guinea-Bissau"),
    GUY(false, "Guyana"),
    HTI(false, "Haiti"),
    HMD(false, "Heard- og McDonaldøyene"),
    GRC(true, "Hellas"),
    HND(false, "Honduras"),
    HKG(false, "Hongkong"),
    IND(true, "India"),
    IDN(false, "Indonesia"),
    IRQ(false, "Irak"),
    IRN(false, "Iran"),
    IRL(true, "Irland"),
    ISL(true, "Island"),
    IMN(true, "Isle of Man"),
    ISR(true, "Israel"),
    ITA(true, "Italia"),
    JAM(false, "Jamaica"),
    JPN(false, "Japan"),
    JEY(true, "Jersey"),
    JOR(false, "Jordan"),
    KHM(false, "Kambodsja"),
    CMR(false, "Kamerun"),
    CPV(false, "Kapp Verde"),
    KAZ(false, "Kasakhstan"),
    KEN(false, "Kenya"),
    CHN(false, "Kina"),
    KGZ(false, "Kirgisistan"),
    KIR(false, "Kiribati"),
    CCK(false, "Kokosøyene (Keelingøyene)"),
    COM(false, "Komorene"),
    COD(false, "Kongo"),
    COG(false, "Kongo-Brazzaville"),
    XXK(false, "Kosovo"),
    HRV(true, "Kroatia"),
    KWT(false, "Kuwait"),
    CYP(true, "Kypros"),
    LAO(false, "Laos"),
    LVA(true, "Latvia"),
    LSO(false, "Lesotho"),
    LBN(false, "Libanon"),
    LBR(false, "Liberia"),
    LBY(false, "Libya"),
    LIE(true, "Liechtenstein"),
    LTU(true, "Litauen"),
    LUX(true, "Luxembourg"),
    MAC(false, "Macao"),
    MDG(false, "Madagaskar"),
    MWI(false, "Malawi"),
    MYS(false, "Malaysia"),
    MDV(false, "Maldivene"),
    MLI(false, "Mali"),
    MLT(true, "Malta"),
    MAR(false, "Marokko"),
    MHL(false, "Marshalløyene"),
    MTQ(true, "Martinique"),
    MRT(false, "Mauritania"),
    MUS(false, "Mauritius"),
    MYT(false, "Mayotte"),
    MEX(false, "Mexico"),
    FSM(false, "Mikronesiaføderasjonen"),
    MDA(false, "Moldova"),
    MCO(false, "Monaco"),
    MNG(false, "Mongolia"),
    MNE(false, "Montenegro"),
    MSR(false, "Montserrat"),
    MOZ(false, "Mosambik"),
    MMR(false, "Myanmar (Burma)"),
    NAM(false, "Namibia"),
    NRU(false, "Nauru"),
    NLD(true, "Nederland"),
    NPL(false, "Nepal"),
    NZL(false, "New Zealand"),
    NIC(false, "Nicaragua"),
    NER(false, "Niger"),
    NGA(false, "Nigeria"),
    NIU(false, "Niue"),
    PRK(false, "Nord-Korea"),
    MKD(false, "Nord-Makedonia"),
    MNP(false, "Nord-Marianene"),
    NFK(false, "Norfolkøya"),
    NOR(true, "Norge"),
    NCL(false, "Ny-Caledonia"),
    OMN(false, "Oman"),
    PAK(false, "Pakistan"),
    PLW(false, "Palau"),
    PSE(false, "Palestina"),
    PAN(false, "Panama"),
    PNG(false, "Papua Ny-Guinea"),
    PRY(false, "Paraguay"),
    PER(false, "Peru"),
    PCN(false, "Pitcairn"),
    POL(true, "Polen"),
    PRT(true, "Portugal"),
    PRI(false, "Puerto Rico"),
    QAT(false, "Qatar"),
    QEB(true, "Quebec"),
    REU(true, "Reunion"),
    ROU(true, "Romania"),
    RUS(false, "Russland"),
    RWA(false, "Rwanda"),
    BLM(false, "Saint Barthelemy"),
    KNA(false, "Saint Kitts og Nevis"),
    LCA(false, "Saint Lucia"),
    MAF(false, "Saint Martin"),
    VCT(false, "Saint Vincent og Grenadinene"),
    SPM(false, "Saint-Pierre og Miquelon"),
    SLB(false, "Salomonøyene"),
    WSM(false, "Samoa"),
    SMR(false, "San Marino"),
    SHN(false, "Sankt Helena, Ascension og Tristan da Cunha"),
    STP(false, "Sao Tome Og Principe"),
    SAU(false, "Saudi-Arabia"),
    SEN(false, "Senegal"),
    SRB(false, "Serbia"),
    SYC(false, "Seychellene"),
    SLE(false, "Sierra Leone"),
    SGP(false, "Singapore"),
    SXM(false, "Sint Maarten"),
    SVK(true, "Slovakia"),
    SVN(true, "Slovenia"),
    SOM(false, "Somalia"),
    ESP(true, "Spania"),
    LKA(false, "Sri Lanka"),
    XXX(false, "Statløs"),
    GBR(true, "Storbritannia"),
    SDN(false, "Sudan"),
    SUR(false, "Suriname"),
    SJM(false, "Svalbard og Jan Mayen"),
    CHE(true, "Sveits"),
    SWE(true, "Sverige"),
    SYR(false, "Syria"),
    ZAF(false, "Sør-Afrika"),
    SGS(false, "Sør-Georgia og Sør-Sandwichøyene"),
    KOR(true, "Sør-Korea"),
    SSD(false, "Sør-Sudan"),
    TJK(false, "Tadsjikistan"),
    TWN(false, "Taiwan"),
    TZA(false, "Tanzania"),
    TCD(false, "Tchad"),
    THA(false, "Thailand"),
    TGO(false, "Togo"),
    TKL(false, "Tokelau"),
    TON(false, "Tonga"),
    TTO(false, "Trinidad Og Tobago"),
    CZE(true, "Tsjekkia"),
    TUN(false, "Tunisia"),
    TKM(false, "Turkmenistan"),
    TCA(false, "Turks- og Caicosøyene"),
    TUV(false, "Tuvalu"),
    TUR(false, "Tyrkia"),
    DEU(true, "Tyskland"),
    USA(true, "USA"),
    UGA(false, "Uganda"),
    UKR(false, "Ukraina"),
    HUN(true, "Ungarn"),
    XUK(false, "Uoppgitt/Ukjent"),
    URY(false, "Uruguay"),
    UMI(false, "Usas ytre småøyer"),
    UZB(false, "Usbekistan"),
    VUT(false, "Vanuatu"),
    VAT(false, "Vatikanstaten"),
    VEN(false, "Venezuela"),
    ESH(false, "Vest-Sahara"),
    VNM(false, "Vietnam"),
    WLF(false, "Wallis og Futuna"),
    YEM(false, "Yemen"),
    ZMB(false, "Zambia"),
    ZWE(false, "Zimbabwe"),
    TLS(false, "Øst-Timor"),
    AUT(true, "Østerrike"),
    ALA(false, "Åland")
}
